[book]
title = "ç°ä»£æ¨ç®±å­æ•™ç¨‹"
description = "æœ¬æ–‡å°†æè¿°å¦‚ä½•å®ç°ä¸€ä¸ªæ¨ç®±å­ ğŸ“¦, ç¤ºä¾‹ä»£ç ä½¿ç”¨ Rust è¯­è¨€ ğŸ¦€ ç¼–å†™."
authors = ["ShenMian <sms_school@outlook.com>"]
language = "zh-Hans-CN"
multilingual = false
src = "src"

[output.html]
additional-js = ["assets/mermaid.min.js", "assets/mermaid-init.js"]
git-repository-url = "https://github.com/ShenMian/sokoban-tutorial"
git-repository-icon = "fa-github"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.katex]
after = ["links"]
